from collections import deque

# EventPool class is used to store all the events that are generated by the application.
# It has a pool of events with a maximum size of 100.


class EventPool:
    def __init__(self, size=100):
        self.pool = deque(maxlen=size)

    def add_event(self, event):
        self.pool.append(event)

    def get_all_events(self):
        return list(self.pool)

event_pool = EventPool()