version: '3.9'

networks:
  app_network:
    driver: bridge

services:
  backend:
    build: .
    container_name: smart_house_backend
    networks:
      - app_network
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
    env_file:
      - .env
    depends_on:
      mongo:
        condition: service_healthy
    restart: always

  redis:
    image: redis:7-alpine
    container_name: redis
    networks:
      - app_network
    ports:
      - "6379:6379"
    restart: unless-stopped

  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt_broker
    networks:
      - app_network
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    restart: always

  mongo:
    image: mongo:7.0
    container_name: smart_house_db
    networks:
      - app_network
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./docker/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=smart_house_db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' \| mongosh --quiet --username admin --password admin --authenticationDatabase admin
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    command:
      - "--auth"
      - "--bind_ip_all"
      - "--wiredTigerCacheSizeGB"
      - "1.5"
    restart: always

volumes:
  mongo_data:
