version: "3.8"

# Define services
services:
  # PostgreSQL database
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: smart_house_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  # Redis broker
  redis:
    image: redis:7
    container_name: redis_broker
    restart: always
    ports:
      - "6379:6379"

  # FastAPI backend
  backend:
    build: .
    container_name: fastapi_backend
    restart: always
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: "postgresql://myuser:mypassword@db:5432/smart_house_db"
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/0"
    ports:
      - "8000:8000"

  # Celery worker
  worker:
    build: .
    container_name: celery_worker
    restart: always
    depends_on:
      - backend
      - redis
    environment:
      DATABASE_URL: "postgresql://myuser:mypassword@db:5432/smart_house_db"
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/0"
    command: ["celery", "-A", "app.workers.celery_worker", "worker", "--loglevel=info"]

  # Celery Flower monitoring tool
  flower:
    image: mher/flower
    container_name: celery_flower
    restart: always
    depends_on:
      - redis
      - worker
    environment:
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/0"
    ports:
      - "5555:5555"

# Define volumes
volumes:
  pg_data: